# Generated by Django 5.1.7 on 2025-05-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
    ]
